theme: minima
title: Aaron Putty's Skyrim Modding Blog
author: Aaron Putty
description: A log of history, thoughts, and rationale behind Aaron Putty's skyim modding ideas. Reasoning and ideas about a modlist.
